import type { CardDataState } from 'core/Cards/CardEntity/CardEntity.interfaces';

const initialCardState: CardDataState = {
    data: {
        '43114': {
            apr: null,
            currentDeposits: null,
            totalDeposits: null,
            available: null,
            totalAvailable: null,
            price: null,
            yieldTime: null,
            positions: null,
            totalPositions: null,
            localName: 'AVAX',
            localChain: '43114',
        },
        '56': {
            apr: null,
            currentDeposits: null,
            totalDeposits: null,
            available: null,
            totalAvailable: null,
            price: null,
            yieldTime: null,
            positions: null,
            totalPositions: null,
            localName: 'BSC',
            localChain: '56',
        },
        '250': {
            apr: null,
            currentDeposits: null,
            totalDeposits: null,
            available: null,
            totalAvailable: null,
            price: null,
            yieldTime: null,
            positions: null,
            totalPositions: null,
            localName: 'FTM',
            localChain: '250',
        },
        '1': {
            apr: null,
            currentDeposits: null,
            totalDeposits: null,
            available: null,
            totalAvailable: null,
            price: null,
            yieldTime: null,
            positions: null,
            totalPositions: null,
            localName: 'ETH',
            localChain: '1',
        },
        '22417': {
            apr: '10.4',
            currentDeposits: '124',
            totalDeposits: '124',
            available: '22',
            totalAvailable: '2',
            price: '4.5',
            yieldTime: '4',
            positions: '1',
            totalPositions: '1',
            localName: 'EGLD',
            localChain: '22417',
        },
    },
};

export {
    initialCardState,
};
